name: creditcardfraud
maintainers:
- e4fd1175-34c1-459e-8f4f-ad338c22c963
platforms:
- linux-64
environments:
  default:
  - environment.yaml
commands:
  serve:
    cmd: panel serve creditcardfraud.ipynb
